### ISSUE TITLE
How do I get qry_pts for my own model?

### ISSUE THREAD

**Issue by rhodaliu17** [yizhiwang96/ARO-Net#1]
Hi, this is really an amazing work!

I met with some problems when dealing with my own 3d models, I don't know the specific rules of getting qry_pts for every model. If it is convenient, can you provide some code or some ideas on how to select qry_pts?

Thanks a lot!

**Comment by yizhiwang96** [comment]
> Hi, this is really an amazing work!
> 
> I met with some problems when dealing with my own 3d models, I don't know the specific rules of getting qry_pts for every model. If it is convenient, can you provide some code or some ideas on how to select qry_pts?
> 
> Thanks a lot!

Hi @RhodaLiu17 , Thank you for your interest in our work!

Regarding how to sample qry_pts, I followed [the script](https://github.com/ErlerPhilipp/points2surf/blob/2af6e0facf58422ed12e0c676c70199cd0dfbb43/make_dataset.py#L406C24-L406C46) in [Points2Surf](https://github.com/ErlerPhilipp/points2surf) to sample qry_pts and calculate their signed distance. Note that I did not use [their way of normalization](https://github.com/ErlerPhilipp/points2surf/blob/2af6e0facf58422ed12e0c676c70199cd0dfbb43/make_dataset.py#L71), our way of normalization can be found in [this link](https://github.com/yizhiwang96/ARO-Net/blob/main/data_processing/norm_and_sample_mesh.py), where the length of body diagonal of 3D bounding box is normalized to 1.

Recently I also found [another script](https://github.com/yccyenchicheng/SDFusion/blob/bee6119cb4cab85ebe7d42d32f223ef30795abf0/preprocess/create_sdf.py#L904) to sample qry_pts and calculate their signed distance, which is a C++ program and runs very fast.

**Comment by rhodaliu17** [comment]
> > Hi, this is really an amazing work!
> > I met with some problems when dealing with my own 3d models, I don't know the specific rules of getting qry_pts for every model. If it is convenient, can you provide some code or some ideas on how to select qry_pts?
> > Thanks a lot!
> 
> Hi @RhodaLiu17 , Thank you for your interest in our work!
> 
> Regarding how to sample qry_pts, I followed [the script](https://github.com/ErlerPhilipp/points2surf/blob/2af6e0facf58422ed12e0c676c70199cd0dfbb43/make_dataset.py#L406C24-L406C46) in [Points2Surf](https://github.com/ErlerPhilipp/points2surf) to sample qry_pts and calculate their signed distance. Note that I did not use [their way of normalization](https://github.com/ErlerPhilipp/points2surf/blob/2af6e0facf58422ed12e0c676c70199cd0dfbb43/make_dataset.py#L71), our way of normalization can be found in [this link](https://github.com/yizhiwang96/ARO-Net/blob/main/data_processing/norm_and_sample_mesh.py), where the length of body diagonal of 3D bounding box is normalized to 1.
> 
> Recently I also found [another script](https://github.com/yccyenchicheng/SDFusion/blob/bee6119cb4cab85ebe7d42d32f223ef30795abf0/preprocess/create_sdf.py#L904) to sample qry_pts and calculate their signed distance, which is a C++ program and runs very fast.

Thanks for your reply!

**Comment by yizhiwang96** [comment]
> > > Hi, this is really an amazing work!
> > > I met with some problems when dealing with my own 3d models, I don't know the specific rules of getting qry_pts for every model. If it is convenient, can you provide some code or some ideas on how to select qry_pts?
> > > Thanks a lot!
> > 
> > 
> > Hi @RhodaLiu17 , Thank you for your interest in our work!
> > Regarding how to sample qry_pts, I followed [the script](https://github.com/ErlerPhilipp/points2surf/blob/2af6e0facf58422ed12e0c676c70199cd0dfbb43/make_dataset.py#L406C24-L406C46) in [Points2Surf](https://github.com/ErlerPhilipp/points2surf) to sample qry_pts and calculate their signed distance. Note that I did not use [their way of normalization](https://github.com/ErlerPhilipp/points2surf/blob/2af6e0facf58422ed12e0c676c70199cd0dfbb43/make_dataset.py#L71), our way of normalization can be found in [this link](https://github.com/yizhiwang96/ARO-Net/blob/main/data_processing/norm_and_sample_mesh.py), where the length of body diagonal of 3D bounding box is normalized to 1.
> > Recently I also found [another script](https://github.com/yccyenchicheng/SDFusion/blob/bee6119cb4cab85ebe7d42d32f223ef30795abf0/preprocess/create_sdf.py#L904) to sample qry_pts and calculate their signed distance, which is a C++ program and runs very fast.
> 
> Thanks for your reply!

You're welcome. If you have any other question, pls don't hesitate to tell us.
